Add formatting check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,6 +25,49 @@ jobs:
         echo "::set-output name=version::$VERSION"
         echo $VERSION
 
+  format:
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.ref }}
+        fetch-depth: 0
+        submodules: true
+
+    - name: Install .NET Core
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 6.x
+
+    - name: Install ReSharper
+      run: |
+        dotnet tool install -g JetBrains.ReSharper.GlobalTools
+
+    - name: Restore
+      run: |
+        dotnet restore Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj
+
+    - name: Reformat
+      run: |
+        jb cleanupcode Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj
+
+    - name: Check Diff
+      continue-on-error: true
+      run: |
+        DIFF="$(git diff --name-only)"
+
+        if [ -z "$DIFF" ]; then
+          echo "OK: Format is clean"
+        else
+          echo "Error: Format was not clean"
+          echo "List of files:"
+          echo "$DIFF"
+          git diff
+          exit 1
+        fi
+
   build:
     runs-on: ubuntu-latest
     needs: versionning
