Adding gtest support in CMakeLists and code formating and build in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,6 +76,56 @@ jobs:
             exit 1
           fi
 
+  format-cpp:
+    name: Format C++
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    strategy:
+      matrix:
+        path:
+          - packages/cpp/ArmoniK.Api.Client
+          - packages/cpp/ArmoniK.Api.Common
+          - packages/cpp/ArmoniK.Api.Worker
+          - packages/cpp/ArmoniK.Api.Tests
+          - packages/cpp/ArmoniK.Api.Worker.Tests
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.ref }}
+          fetch-depth: 0
+          submodules: true
+
+      - name: Run clang-format
+        - uses: jidicula/clang-format-action@v4.11.0
+          with:
+            clang-format-version: '13'
+            check-path: ${{ matrix.path }}
+
+      - name: Check Diff
+        run: |
+          DIFF="$(git diff --name-only)"
+
+          if [ -z "$DIFF" ]; then
+            echo "OK: Format is clean"
+          else
+            echo "Error: Format was not clean"
+            echo "List of files:"
+            echo "$DIFF"
+            git diff
+            exit 1
+          fi
+
+    - name: Generate patch
+      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
+      run: |
+        git diff > patch-cpp.diff
+    - uses: actions/upload-artifact@v3
+      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
+      with:
+        name: patch-cpp
+        path: ./patch-cpp.diff
+
   format-protobuf:
     name: Format Protobuf
     runs-on: ubuntu-latest
